### ISSUE TITLE
muscleserver.py doesn't work

### ISSUE THREAD

**Issue by kzfm** [Serulab/Py4Bio#16]
Dear Seulab, 

When running muscleserver.py, I got two errors.

```
  File "muscleserver.py", line 38, in result
    fi_fh.write(sequence)
TypeError: a bytes-like object is required, not 'str'
```

```
    % if bad_option:
NameError: name 'bad_option' is not defined
```

For the latter one, I fixed it by changing "bad_opt" in line 55  to "bad_option". 

And for the former one, I changed "fi_fh.write(sequence)" in line 38 to "fi_fh.write(sequence.encode(’utf-8’))" but I'm not sure this is right way.

Could you give me some advice?

**Comment by sbassi** [comment]
will research this

**Comment by sbassi** [comment]
I reproduced the error, will fix it during this day.

**Comment by sbassi** [comment]
I made the changes, it works for me now. Please check it. There were changes in the py file and in the template file.
Thank you for your support.

**Comment by kzfm** [comment]
Dear @sbassi,
Thank you for your quick fix, now it works well!
