### ISSUE TITLE
primer31.py doesn't work

### ISSUE THREAD

**Issue by kzfm** [Serulab/Py4Bio#18]
Dear @sbassi,

When I run primer3 using the file generated with primer31.py I got the following error.

```
$ ./primer3_core < swforprimer3.txt
...
PRIMER_PRODUCT_SIZE_RANGE=45-57544
PRIMER_ERROR=thermodynamic approach chosen, but path to thermodynamic parameters not specified
=
```

I fixed it by changing the template like this,
https://github.com/Serulab/Py4Bio/tree/master/code/ch17

```
PRIMER_SEQUENCE_ID={title}
SEQUENCE_TEMPLATE={seq}
TARGET={pos},{win_size}
PRIMER_OPT_SIZE=18
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=20
PRIMER_NUM_NS_ACCEPTED=0
PRIMER_EXPLAIN_FLAG=1
PRIMER_PRODUCT_SIZE_RANGE={win_size}-{len_seq}
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=primer3-2.4.0/src/primer3_config/
=
```

- Added "=" at the end of the template.
- Change "SEQUENCE" to "SEQUENCE_TEMPLATE".
- Added "PRIMER_THERMODYNAMIC_PARAMETERS_PATH" option.

https://www.biostars.org/p/355320/
https://primer3.org/manual.html#inputOutputConventions

Could you check these and give me any advice?

Best regards,
kzfm

**Comment by kzfm** [comment]
When I placed primer3_config dir in the same directory at the primer3_core executable, I didn't need to add PRIMER_THERMODYNAMIC_PARAMETERS_PATH to the template file.

**Comment by sbassi** [comment]
hello, yes, first 2 changes are OK, but I will not update the path parameter, will update the book stating that the primer3_core must be in the same directory on in the system path..

**Comment by kzfm** [comment]
Thank you for replying. It works well now but when running it from biopython(primer32.py), I got the same error.

```

from Bio import SeqIO
from Bio.Emboss.Applications import Primer3Commandline

INPUT_SEQUENCE = '../../samples/hsc1.fasta'
OUTPUT_SEQUENCE = 'primer.txt'
sfile = open('../../samples/hsc1.fasta')
myseq = SeqIO.read(sfile, 'fasta')
title = myseq.id
seq = str(myseq.seq).upper()
win_size = 45
i = 0
number_l = []
while i <= (len(seq) - win_size):
    number_l.append(seq[i:i + win_size].count('AAT'))
    i += 1 # This is the same as i = i+1
pos = number_l.index(max(number_l))
pr_cl = Primer3Commandline(sequence=INPUT_SEQUENCE, auto=True)
pr_cl.outfile = OUTPUT_SEQUENCE
pr_cl.osize = 18
pr_cl.maxsize = 20
pr_cl.minsize = 15
pr_cl.explainflag = 1
pr_cl.target = "{},{}".format(pos, pos+win_size)
pr_cl.prange = "{},{}".format(win_size, len(seq))
r,e = pr_cl()
print(e)
# Error: Missing SEQUENCE tag

```
The versions I tried were: Biopython1.76 and primer3(libprimer3 release 2.4.0).

I found that it's come from eprimer3 which Primer3Commandline call and eprimer3 doesn't support the newer version of primer3.

https://github.com/biopython/biopython/issues/485
https://www.biostars.org/p/102268/

> From a quick check in the EMBOSS documentation for eprimer3, it is intended for use with the old primer3 releases (i.e. version 1 or eariler). 

How can I fix this problem? Could you give me any advice?

**Comment by sbassi** [comment]
Regarding primer32.py, I believe that since the new version of primer3 is not compatible with eprimer, and since primer3 needs to generate a configuration file rather than passing everything by command line, I think the best course of action is to remove this code. Let me modify the book tomorrow.
